// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfzwN1vck3Cuvz2e_1FxiCl372SpxnJBY',
    appId: '1:882798406052:web:287773e8362b6f40a53931',
    messagingSenderId: '882798406052',
    projectId: 'graduation-project-2d09b',
    authDomain: 'graduation-project-2d09b.firebaseapp.com',
    storageBucket: 'graduation-project-2d09b.firebasestorage.app',
    measurementId: 'G-2LH7HE576L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc3kwxlgis14bwfk78EDp7pOkag9qH2dc',
    appId: '1:882798406052:android:4826166fa16c204ba53931',
    messagingSenderId: '882798406052',
    projectId: 'graduation-project-2d09b',
    storageBucket: 'graduation-project-2d09b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcTDhAouBQ5QzY8Z4zkTy819Lb1t9cNwk',
    appId: '1:882798406052:ios:3ce8edde7590a7eda53931',
    messagingSenderId: '882798406052',
    projectId: 'graduation-project-2d09b',
    storageBucket: 'graduation-project-2d09b.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcTDhAouBQ5QzY8Z4zkTy819Lb1t9cNwk',
    appId: '1:882798406052:ios:3ce8edde7590a7eda53931',
    messagingSenderId: '882798406052',
    projectId: 'graduation-project-2d09b',
    storageBucket: 'graduation-project-2d09b.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfzwN1vck3Cuvz2e_1FxiCl372SpxnJBY',
    appId: '1:882798406052:web:92de7220d434f31fa53931',
    messagingSenderId: '882798406052',
    projectId: 'graduation-project-2d09b',
    authDomain: 'graduation-project-2d09b.firebaseapp.com',
    storageBucket: 'graduation-project-2d09b.firebasestorage.app',
    measurementId: 'G-P7KCLZ2PBL',
  );
}
